name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
     
    - name: Retrieve Google Test
      run: cp -r ~/actions-runner-local/googletest ./googletest


    - name: Build and Run Reg File
      run: make runtest RUN=module GTEST=1 MODULE=reg_file MODULE.INCLUDE_DIRS="" && make clean

    - name: Build and Run ALU
      run: make runtest GTEST=1 RUN=module MODULE=alu MODULE.INCLUDE_DIRS=""  && make clean

    - name: Build and Run Sign Extend
      run: make runtest RUN=module GTEST=1 MODULE=sign_extend MODULE.INCLUDE_DIRS="" && make clean

    - name: Build and Run Data Memory Wrapper
      run: make runtest RUN=module GTEST=1 MODULE=data_mem_wrapper MODULE.INCLUDE_DIRS="-y rtl/data_mem -y rtl/we_decoder -y rtl/ld_decoder" && make clean

    - name: Build and Run Control Unit
      run: make runtest RUN=module GTEST=1 MODULE=control_unit MODULE.INCLUDE_DIRS="-y rtl/control_unit/decoders" && make clean
      
    - name: Build and Run Top Level Testbench
      run: make runtest RUN=unit GTEST=0
