name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Verilator
      run: | 
        sudo apt-get update -q
        sudo apt-get install -y verilator

      
    - name: Install Google Test
      run: make gtest

    - name: Build and Test
      run: make runtest
