name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Cache Google Test
      uses: actions/cache@v2
      with:
        path: |
          googletest/
        key: ${{ runner.os }}-gtest-${{ hashFiles('**/googletest') }}
     
    - name: Install Google Test
      run: make gtest

    - name: Build and Run Control Unit
      run: make runtest MODULE=control_unit MODULE.INCLUDE_DIRS="-y design/control_unit/decoders" && make clean

    - name: Build and Run Reg File
      run: make runtest MODULE=reg_file MODULE.INCLUDE_DIRS="" && make clean
